stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  pre_processing:
    cmd: python3 src/pre_processing.py
    deps:
    - data/raw
    - src/pre_processing.py
    outs:
    - data/process_data
  feature_eng:
    cmd: python3 src/feature_eng.py
    deps:
    - data/process_data
    - src/feature_eng.py
    outs:
    - data/featureData
  model_building:
    cmd: python3 src/model_building.py
    deps:
    - data/featureData
    - src/model_building.py
    outs:
    - models/model.pkl
  model_evalution:
    cmd: python3 src/model_evalution.py
    deps:
    - models/model.pkl
    - src/model_evalution.py
    outs:
    - reports/metrics.json
